# Generated by Django 3.1.2 on 2021-02-25 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cookie_consent',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 20, 59, 58, 196331), null=True),
        ),
    ]
