# Generated by Django 3.1.2 on 2021-02-25 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_cookie_consent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cookie_consent',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 21, 5, 21, 10159), null=True),
        ),
    ]
